// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PoolConfigurator$Type } from "./PoolConfigurator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PoolConfigurator"]: PoolConfigurator$Type;
    ["aave-v3-core/protocol/pool/PoolConfigurator.sol:PoolConfigurator"]: PoolConfigurator$Type;
  }

  interface ContractTypesMap {
    ["PoolConfigurator"]: GetContractReturnType<PoolConfigurator$Type["abi"]>;
    ["aave-v3-core/protocol/pool/PoolConfigurator.sol:PoolConfigurator"]: GetContractReturnType<PoolConfigurator$Type["abi"]>;
  }
}
