// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DefaultReserveInterestRateStrategy$Type } from "./DefaultReserveInterestRateStrategy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DefaultReserveInterestRateStrategy"]: DefaultReserveInterestRateStrategy$Type;
    ["aave-v3-core/contracts/protocol/pool/DefaultReserveInterestRateStrategy.sol:DefaultReserveInterestRateStrategy"]: DefaultReserveInterestRateStrategy$Type;
  }

  interface ContractTypesMap {
    ["DefaultReserveInterestRateStrategy"]: GetContractReturnType<DefaultReserveInterestRateStrategy$Type["abi"]>;
    ["aave-v3-core/contracts/protocol/pool/DefaultReserveInterestRateStrategy.sol:DefaultReserveInterestRateStrategy"]: GetContractReturnType<DefaultReserveInterestRateStrategy$Type["abi"]>;
  }
}
