// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { L2Pool$Type } from "./L2Pool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["L2Pool"]: L2Pool$Type;
    ["aave-v3-core/protocol/pool/L2Pool.sol:L2Pool"]: L2Pool$Type;
  }

  interface ContractTypesMap {
    ["L2Pool"]: GetContractReturnType<L2Pool$Type["abi"]>;
    ["aave-v3-core/protocol/pool/L2Pool.sol:L2Pool"]: GetContractReturnType<L2Pool$Type["abi"]>;
  }
}
