# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Check
on:
  workflow_call:
    inputs:
      skip-format-and-type:
        description: 'Whether to skip step that format, lint, and check type or not. Default to false.'
        default: false
        type: boolean
        required: false

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up and install
        uses: ./.github/actions/setup-and-install

      - if: ${{ inputs.skip-format-and-type == false }}
        name: Format and lint code
        run: bun run format && bun run lint

      - if: ${{ inputs.skip-format-and-type == false }}
        name: Check code types
        run: bun run typecheck

      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run test
        run: bun run test:coverage
        env:
          VITE_ARBITRUM_RPC_URL: ${{ secrets.VITE_ARBITRUM_RPC_URL }}
          SEPOLIA_ARBISCAN_API_KEY: ${{ secrets.SEPOLIA_ARBISCAN_API_KEY }}
          HOLESKY_ETHERSCAN_API_KEY: ${{ secrets.HOLESKY_ETHERSCAN_API_KEY }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Auto commit new changes from format and lint
      # ref: https://github.com/stefanzweifel/git-auto-commit-action
      - if: ${{ inputs.skip-format-and-type == false }}
        name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format and lint'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
