# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Check
on:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up and install
        uses: ./.github/actions/setup-and-install

      - name: Format and lint code
        run: bun run format && bun run lint

      - name: Check code types
        run: bun run typecheck

      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false

      - name: Run test
        run: bun run test:coverage
        env:
          VITE_ARBITRUM_RPC_URL: ${{ secrets.VITE_ARBITRUM_RPC_URL }}
          SEPOLIA_ARBISCAN_API_KEY: ${{ secrets.SEPOLIA_ARBISCAN_API_KEY }}
          HOLESKY_ETHERSCAN_API_KEY: ${{ secrets.HOLESKY_ETHERSCAN_API_KEY }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
