# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Pull request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit

  # size:
  #   name: Size
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up and install
  #       uses: ./.github/actions/setup-and-install

  #       # ref: https://github.com/preactjs/compressed-size-action
  #     - name: Report build size
  #       uses: preactjs/compressed-size-action@v2
  #       with:
  #         pattern: 'packages/**/dist/**'
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
