# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Pull request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit
