# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Release
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit

  changesets:
    name: Changesets
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          submodules: true

      - name: Set up and install
        uses: ./.github/actions/setup-and-install

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'Release'
          commit: 'update packages version'
          version: bun changeset:version
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
          publish: bun changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
